"""
backup_gen.py — Generate daily_backup.py from WizardState.

Docker context:
- Workspaces are inside the container at /home/node/.openclaw/workspace
- Backup medium is mounted into the container via docker-compose.yml
- Script runs inside the container (via docker compose exec or cron)

Backup strategy (matches reference implementation):
- Mon–Sat: incremental rsync (--checksum, changed files only)
- Sunday:  full rsync + versioned copy to versions/YYYY-MM-DD/
- Retention: 30 days for versioned snapshots
- exec-approvals.json: token REDACTED in backup

What is backed up:
- workspace/ (MEMORY.md, tasks/, topics/, skills/ etc.)
- openclaw.json, exec-approvals.json (token=REDACTED), scripts/*.py

What is NOT backed up:
- .env / API keys (never)
- session JSONL, *.log, *.tmp
- node_modules/, dist/, .astro/, .git/
"""
from pathlib import Path
from wizard.state import WizardState

# Container-internal paths
_OPENCLAW  = "/home/node/.openclaw"
_WORKSPACE = f"{_OPENCLAW}/workspace"


def generate(state: WizardState) -> str:
    backup_mount = state.backup_mount_path or "/mnt/backup"

    return f'''#!/usr/bin/env python3
"""
daily_backup.py — Daily OpenClaw backup inside the container.
Generated by openclaw-installer. Re-run installer to regenerate.

Schedule (add to host crontab or systemd timer):
  10 4 * * * docker compose -f {state.openclaw_dir}/docker-compose.yml \\
      exec -T openclaw-gateway python3 /home/node/.openclaw/scripts/daily_backup.py

Strategy:
  Mon-Sat: incremental rsync (changed files only)
  Sunday:  full rsync + versioned snapshot
  Retention: 30 days for versioned snapshots

Backup medium: {backup_mount}  (mounted into container)
"""
import json
import logging
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

OPENCLAW    = Path("{_OPENCLAW}")
WORKSPACE   = Path("{_WORKSPACE}")
BACKUP_MOUNT = Path("{backup_mount}")
BACKUP_DIR  = BACKUP_MOUNT / "openclaw-backup"
LOG_FILE    = BACKUP_DIR / "backup.log"

RSYNC_EXCLUDES = [
    "--exclude=.git/",
    "--exclude=*.log",
    "--exclude=*.tmp",
    "--exclude=node_modules/",
    "--exclude=dist/",
    "--exclude=.astro/",
    "--exclude=.venv/",
]


def setup_logging() -> None:
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    logging.basicConfig(
        filename=str(LOG_FILE),
        level=logging.INFO,
        format="[%(asctime)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        force=True,
    )
    logging.getLogger().addHandler(logging.StreamHandler(sys.stdout))


log = logging.getLogger()


def check_mount() -> None:
    if not BACKUP_MOUNT.is_mount() and not BACKUP_MOUNT.exists():
        print(f"ERROR: Backup mount not available: {{BACKUP_MOUNT}} — aborting.")
        sys.exit(1)
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    log.info("Backup mount available: %s", BACKUP_MOUNT)


def backup_workspace(is_sunday: bool, date_str: str) -> None:
    dst = BACKUP_DIR / "workspace"
    dst.mkdir(parents=True, exist_ok=True)

    cmd = ["rsync", "--archive", "--checksum", "--delete", "--quiet"] + RSYNC_EXCLUDES

    if is_sunday:
        versions_dir = BACKUP_DIR / "versions" / date_str / "workspace"
        versions_dir.mkdir(parents=True, exist_ok=True)
        cmd += [f"--backup", f"--backup-dir={{str(versions_dir)}}"]

    cmd += [f"{{str(WORKSPACE)}}/", str(dst) + "/"]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode not in (0, 24):  # 24 = vanished source files (ok)
        log.warning("rsync warning for workspace: %s", result.stderr.strip())
    log.info("Backed up: workspace")


def backup_config() -> None:
    dst = BACKUP_DIR / "openclaw-config"
    dst.mkdir(parents=True, exist_ok=True)

    # openclaw.json
    src_cfg = OPENCLAW / "openclaw.json"
    if src_cfg.exists():
        shutil.copy2(src_cfg, dst / "openclaw.json")
        log.info("Backed up: openclaw.json")

    # scripts/*.py
    scripts_dst = dst / "scripts"
    scripts_dst.mkdir(exist_ok=True)
    src_scripts = OPENCLAW / "scripts"
    if src_scripts.exists():
        for f in src_scripts.iterdir():
            if f.is_file() and f.suffix == ".py":
                shutil.copy2(f, scripts_dst / f.name)
        log.info("Backed up: scripts/")

    # exec-approvals.json — token REDACTED
    approvals_src = OPENCLAW / "exec-approvals.json"
    if approvals_src.exists():
        try:
            data = json.loads(approvals_src.read_text())
            if "socket" in data and "token" in data["socket"]:
                data["socket"]["token"] = "REDACTED"
            (dst / "exec-approvals.json").write_text(json.dumps(data, indent=2), encoding="utf-8")
            log.info("Backed up: exec-approvals.json (token redacted)")
        except Exception as exc:
            log.warning("exec-approvals.json backup failed: %s", exc)

    # Memory SQLite indexes (if any)
    memory_db_dst = dst / "memory-db"
    memory_db_dst.mkdir(exist_ok=True)
    for db in OPENCLAW.rglob("*.sqlite"):
        if "sessions" not in str(db):
            try:
                shutil.copy2(db, memory_db_dst / db.name)
                log.info("Backed up: %s", db.name)
            except Exception as exc:
                log.warning("SQLite backup %s: %s", db.name, exc)


def cleanup_old_versions() -> None:
    import time
    versions_dir = BACKUP_DIR / "versions"
    if not versions_dir.exists():
        return
    cutoff = time.time() - 30 * 86400
    for d in versions_dir.iterdir():
        if d.is_dir() and d.stat().st_mtime < cutoff:
            shutil.rmtree(d)
            log.info("Retention: removed %s", d.name)
    log.info("Retention: cleaned up snapshots older than 30 days")


def main() -> None:
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    is_sunday = (now.isoweekday() == 7)

    setup_logging()
    check_mount()

    mode = "Full backup (Sunday)" if is_sunday else "Incremental backup"
    log.info("=== Backup start: %s (%s) ===", date_str, mode)

    backup_workspace(is_sunday, date_str)
    backup_config()

    if is_sunday:
        cleanup_old_versions()

    subprocess.run(["sync"], capture_output=True)
    log.info("=== Backup done: %s ===", date_str)


if __name__ == "__main__":
    main()
'''


def write(state: WizardState) -> Path | None:
    """Write daily_backup.py to scripts_dir. Returns path, or None if skipped."""
    if not state.backup_mount_path:
        return None
    scripts_dir = state.openclaw_dir / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    target = scripts_dir / "daily_backup.py"
    target.write_bytes(generate(state).encode("utf-8"))
    target.chmod(0o755)
    return target
