"""
compose_gen.py — Generate docker-compose.yml from WizardState.
Fetches the current OpenClaw release version from GitHub API and pins it.
Scripts are mounted read-only. Workspace is read-write. .env is read-only.
"""
from pathlib import Path
import httpx
from wizard.state import WizardState

GITHUB_TAGS_URL = "https://api.github.com/repos/openclaw/openclaw/tags"
EXTENDED_STABLE_TAG = "extended-stable"
FALLBACK_IMAGE = f"ghcr.io/openclaw/openclaw:{EXTENDED_STABLE_TAG}"


def fetch_extended_stable_version() -> str:
    """Resolve the OpenClaw extended-stable image tag.

    Strategy:
    1. GitHub Tags API — look up the commit/tag object pointed to by the
       ``extended-stable`` tag. This tag is OpenClaw's stable release pointer;
       the installer deliberately avoids ``latest``.
    2. Fallback: ghcr.io/openclaw/openclaw:extended-stable — always safe,
       tracks the current extended-stable image on the registry.
    """
    # Primary: GitHub Tags API for the extended-stable reference
    try:
        resp = httpx.get(
            GITHUB_TAGS_URL,
            headers={"Accept": "application/vnd.github+json"},
            timeout=10,
            follow_redirects=True,
        )
        resp.raise_for_status()
        tags = resp.json()
        for tag in tags:
            if tag.get("name") == EXTENDED_STABLE_TAG:
                return f"ghcr.io/openclaw/openclaw:{EXTENDED_STABLE_TAG}"
    except Exception:
        pass

    # Fallback: extended-stable alias on the registry
    return FALLBACK_IMAGE


def _vllm_service(state: WizardState) -> str:
    """Return the vLLM Docker Compose service block, or empty string if disabled."""
    if not state.vllm_enabled:
        return ""

    return """
  vllm-qwen:
    image: vllm/vllm-openai:nightly
    container_name: openclaw-vllm-qwen
    runtime: nvidia
    restart: unless-stopped
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    volumes:
      - ${{HF_CACHE}}:/root/.cache/huggingface
    ports:
      - "127.0.0.1:8000:8000"
    command: >
      --model ${{VLLM_MODEL}}
      --gpu-memory-utilization ${{VLLM_GPU_MEMORY_UTILIZATION}}
      --max-model-len ${{VLLM_MAX_MODEL_LEN}}
      --kv-cache-dtype ${{VLLM_KV_CACHE_DTYPE}}
      --enforce-eager
      --reasoning-parser qwen3
      --enable-auto-tool-choice
      --tool-call-parser qwen3_coder
      --chat-template-kwargs '{{"enable_thinking": ${{VLLM_ENABLE_THINKING}}}}'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
"""


def generate(state: WizardState, image: str) -> str:
    """Return docker-compose.yml content as string."""
    openclaw_dir = state.openclaw_dir
    scripts_dir = state.scripts_dir

    compose = f"""# docker-compose.yml — generated by openclaw-installer
# Image pinned at install time. Use 'openclaw-installer update' to upgrade.
# DO NOT edit manually — re-run the installer to regenerate.

services:
  openclaw-gateway:
    image: {image}
    container_name: openclaw-gateway
    restart: unless-stopped

    # start.sh restores exec-approvals.json on every container start
    entrypoint: ["/home/node/.openclaw/scripts/start.sh"]

    env_file:
      - {openclaw_dir}/.env

    ports:
      - "127.0.0.1:18789:18789"

    volumes:
      # Full openclaw config dir — gateway needs write access for temp files and runtime state
      - {openclaw_dir}:/home/node/.openclaw

      # Scripts: read-only (agent cannot modify its own tools)
      - {scripts_dir}:/home/node/.openclaw/scripts:ro

{_backup_mount_line(state)}
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:18789/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

    # Security hardening
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID

    # Resource limits — prevent container from starving the host
    deploy:
      resources:
        limits:
          memory: 2g       # hard cap: OOM-killed if exceeded
          cpus: "2.0"      # max 2 CPU cores
        reservations:
          memory: 256m     # guaranteed minimum
          cpus: "0.25"     # guaranteed minimum

  openclaw-cli:
    image: {image}
    container_name: openclaw-cli
    profiles:
      - cli   # only started explicitly: docker compose --profile cli run openclaw-cli <cmd>
    network_mode: "service:openclaw-gateway"
    env_file:
      - {openclaw_dir}/.env
    volumes:
      - {openclaw_dir}:/home/node/.openclaw
    depends_on:
      - openclaw-gateway
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
{_vllm_service(state)}
"""
    return compose


def _backup_mount_line(state: WizardState) -> str:
    if state.backup_mount_path:
        return f"      # Backup medium\n      - {state.backup_mount_path}:{state.backup_mount_path}"
    return "      # Backup: not configured (skipped during install)"


def write(state: WizardState, image: str) -> Path:
    """Write docker-compose.yml to openclaw_dir. Returns path."""
    target = state.openclaw_dir / "docker-compose.yml"
    target.parent.mkdir(parents=True, exist_ok=True)
    # write_bytes: forces LF endings on Windows — Docker/WSL2 reads this
    # on Linux; CRLF in entrypoint path causes 'file not found' at container start
    target.write_bytes(generate(state, image).encode("utf-8"))
    return target
