"""
compose_gen.py — Generate docker-compose.yml from WizardState.
Fetches the current OpenClaw release version from GitHub API and pins it.
Scripts are mounted read-only. Workspace is read-write. .env is read-only.
"""
from pathlib import Path
import httpx
from wizard.state import WizardState

GHCR_TAGS_URL = "https://ghcr.io/v2/openclaw/openclaw/tags/list"
FALLBACK_IMAGE = "ghcr.io/openclaw/openclaw:latest"


def fetch_latest_version() -> str:
    """Fetch the latest published tag directly from ghcr.io.

    Queries the container registry tag list, picks the most recent
    version tag (e.g. 2026.4.5). Falls back to :latest on any error.
    """
    try:
        # ghcr.io requires an auth token even for public images — use anonymous token
        auth_resp = httpx.get(
            "https://ghcr.io/token?scope=repository:openclaw/openclaw:pull",
            timeout=10,
        )
        auth_resp.raise_for_status()
        token = auth_resp.json().get("token", "")

        resp = httpx.get(
            GHCR_TAGS_URL,
            headers={"Authorization": f"Bearer {token}"},
            timeout=10,
        )
        resp.raise_for_status()
        tags = resp.json().get("tags", [])

        # Filter version-like tags (e.g. 2026.4.5 or v2026.4.5), sort descending
        version_tags = sorted(
            [t for t in tags if t.replace("v", "").replace(".", "").isdigit()],
            reverse=True,
        )
        if version_tags:
            return f"ghcr.io/openclaw/openclaw:{version_tags[0]}"
    except Exception:
        pass
    return FALLBACK_IMAGE


def generate(state: WizardState, image: str) -> str:
    """Return docker-compose.yml content as string."""
    openclaw_dir = state.openclaw_dir
    workspace_dir = state.workspace_dir
    scripts_dir = state.scripts_dir
    logs_dir = openclaw_dir / "logs"
    memory_dir = openclaw_dir / "memory"

    compose = f"""# docker-compose.yml — generated by openclaw-installer
# Image pinned at install time. Use 'openclaw-installer update' to upgrade.
# DO NOT edit manually — re-run the installer to regenerate.

services:
  openclaw-gateway:
    image: {image}
    container_name: openclaw-gateway
    restart: unless-stopped

    # start.sh restores exec-approvals.json on every container start
    entrypoint: ["/home/node/.openclaw/scripts/start.sh"]

    env_file:
      - {openclaw_dir}/.env

    ports:
      - "127.0.0.1:18789:18789"

    volumes:
      # Full openclaw config dir — gateway needs write access for temp files and runtime state
      - {openclaw_dir}:/home/node/.openclaw

      # Scripts: read-only (agent cannot modify its own tools)
      - {scripts_dir}:/home/node/.openclaw/scripts:ro

    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:18789/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

    # Security hardening
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID

  openclaw-cli:
    image: {image}
    container_name: openclaw-cli
    profiles:
      - cli   # only started explicitly: docker compose --profile cli run openclaw-cli <cmd>
    network_mode: "service:openclaw-gateway"
    env_file:
      - {openclaw_dir}/.env
    volumes:
      - {openclaw_dir}:/home/node/.openclaw
    depends_on:
      - openclaw-gateway
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
"""
    return compose


def write(state: WizardState, image: str) -> Path:
    """Write docker-compose.yml to openclaw_dir. Returns path."""
    target = state.openclaw_dir / "docker-compose.yml"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(generate(state, image))
    return target
