"""
compose_gen.py — Generate docker-compose.yml from WizardState.
Fetches the current OpenClaw release version from GitHub API and pins it.
Scripts are mounted read-only. Workspace is read-write. .env is read-only.
"""
from pathlib import Path
import httpx
from wizard.state import WizardState

GITHUB_RELEASES_URL = "https://api.github.com/repos/openclaw/openclaw/releases/latest"
FALLBACK_IMAGE = "ghcr.io/openclaw/openclaw:latest"


def fetch_latest_version() -> str:
    """Fetch the latest OpenClaw release version.

    Strategy (hybrid):
    1. GitHub Releases API — authoritative, always reflects the latest release.
       Constructs image tag from release tag_name (e.g. v2026.4.8 → 2026.4.8).
    2. Fallback: ghcr.io/openclaw/openclaw:latest — always pulls newest image,
       less reproducible but never stale.
    """
    # Primary: GitHub Releases API
    try:
        resp = httpx.get(
            GITHUB_RELEASES_URL,
            headers={"Accept": "application/vnd.github+json"},
            timeout=10,
            follow_redirects=True,
        )
        resp.raise_for_status()
        tag = resp.json().get("tag_name", "")
        if tag:
            # Normalise: strip leading 'v' if present
            version = tag.lstrip("v")
            return f"ghcr.io/openclaw/openclaw:{version}"
    except Exception:
        pass

    # Fallback: :latest
    return FALLBACK_IMAGE


def generate(state: WizardState, image: str) -> str:
    """Return docker-compose.yml content as string."""
    openclaw_dir = state.openclaw_dir
    scripts_dir = state.scripts_dir

    compose = f"""# docker-compose.yml — generated by openclaw-installer
# Image pinned at install time. Use 'openclaw-installer update' to upgrade.
# DO NOT edit manually — re-run the installer to regenerate.

services:
  openclaw-gateway:
    image: {image}
    container_name: openclaw-gateway
    restart: unless-stopped

    # start.sh restores exec-approvals.json on every container start
    entrypoint: ["/home/node/.openclaw/scripts/start.sh"]

    env_file:
      - {openclaw_dir}/.env

    ports:
      - "127.0.0.1:18789:18789"

    volumes:
      # Full openclaw config dir — gateway needs write access for temp files and runtime state
      - {openclaw_dir}:/home/node/.openclaw

      # Scripts: read-only (agent cannot modify its own tools)
      - {scripts_dir}:/home/node/.openclaw/scripts:ro

{_backup_mount_line(state)}
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:18789/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

    # Security hardening
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID

  openclaw-cli:
    image: {image}
    container_name: openclaw-cli
    profiles:
      - cli   # only started explicitly: docker compose --profile cli run openclaw-cli <cmd>
    network_mode: "service:openclaw-gateway"
    env_file:
      - {openclaw_dir}/.env
    volumes:
      - {openclaw_dir}:/home/node/.openclaw
    depends_on:
      - openclaw-gateway
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
"""
    return compose


def _backup_mount_line(state: WizardState) -> str:
    if state.backup_mount_path:
        return f"      # Backup medium\n      - {state.backup_mount_path}:{state.backup_mount_path}"
    return "      # Backup: not configured (skipped during install)"


def write(state: WizardState, image: str) -> Path:
    """Write docker-compose.yml to openclaw_dir. Returns path."""
    target = state.openclaw_dir / "docker-compose.yml"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(generate(state, image))
    return target
