"""
env_gen.py — Generate .env file from WizardState.
Secrets live here only. Never in config files, Docker images, or logs.
"""
from pathlib import Path
from wizard.state import WizardState


# Multi-agent Telegram accounts: included as commented placeholders so users
# can extend the Docker setup without editing generator code.
TELEGRAM_ACCOUNT_EXAMPLES = [
    ("TELEGRAM_BOT_TOKEN_DEFAULT", "Main agent (required)"),
    ("TELEGRAM_BOT_TOKEN_VALERE", "Valère content agent (optional)"),
    ("TELEGRAM_BOT_TOKEN_SENTINEL", "Sentinel security agent (optional)"),
    ("TELEGRAM_BOT_TOKEN_CODING", "Coding agent (optional)"),
    ("TELEGRAM_BOT_TOKEN_SIONIS", "Sionis finance agent (optional)"),
]


def generate(state: WizardState) -> str:
    """Return .env file content as string."""
    lines = [
        "# OpenClaw environment variables",
        "# Generated by openclaw-installer",
        "#",
        "# This file is mounted read-only into the OpenClaw container.",
        "# SecretRefs in openclaw.json resolve values from these variables.",
        "#",
        "# Security: chmod 600, never commit, never share.",
        "",
        f"USER_NAME={state.username}",
        "",
        f"OPENCLAW_GATEWAY_AUTH_TOKEN={state.gateway_auth_token}",
        "",
    ]

    # LLM provider API keys
    if state.anthropic_api_key:
        lines.append(f"ANTHROPIC_API_KEY={state.anthropic_api_key}")
    if state.mistral_api_key:
        lines.append(f"MISTRAL_API_KEY={state.mistral_api_key}")
    if state.aki_api_key:
        lines.append(f"AKI_API_KEY={state.aki_api_key}")
    if state.primary_api_key and state.primary_provider_id not in ("anthropic", "mistral"):
        # Map provider ID to expected env var name
        env_var = _provider_env_var(state.primary_provider_id)
        lines.append(f"{env_var}={state.primary_api_key}")

    # Plugin keys
    if state.brave_web_search_api_key:
        lines.append(f"BRAVE_WEB_SEARCH_API_KEY={state.brave_web_search_api_key}")

    # Channel credentials
    bot_token = state.telegram_bot_token_default or state.telegram_bot_token
    if bot_token:
        lines.append(f"TELEGRAM_BOT_TOKEN_DEFAULT={bot_token}")
    if state.discord_bot_token:
        lines.append(f"DISCORD_BOT_TOKEN={state.discord_bot_token}")
    if state.signal_number:
        lines.append(f"SIGNAL_NUMBER={state.signal_number}")

    # Multi-agent Telegram placeholders (commented)
    lines += ["", "# Optional multi-agent Telegram bot tokens ( uncomment and fill to enable )", "# See docs/telegram-multi-agent.md"]
    for var_name, description in TELEGRAM_ACCOUNT_EXAMPLES[1:]:
        lines.append(f"# {var_name}=<{description.replace(' ', '_')}>")

    lines += [
        "",
        f"LLM_BUDGET={state.llm_budget}",
        f"LLM_STANDARD={state.llm_standard}",
        f"LLM_POWER={state.llm_power}",
        f"LLM_MEDIA={state.llm_media}",
        "",
        f"BACKUP_MOUNT={state.backup_mount_path or '/mnt/backup'}",
    ]

    return "\n".join(lines) + "\n"


def write(state: WizardState) -> Path:
    """Write .env to openclaw_dir. Returns path."""
    env_file = state.env_file
    env_file.parent.mkdir(parents=True, exist_ok=True)
    # write_bytes: forces LF endings (Docker reads .env on Linux/WSL2)
    env_file.write_bytes(generate(state).encode("utf-8"))
    env_file.chmod(0o600)  # owner read/write only
    return env_file


def _provider_env_var(provider_id: str) -> str:
    """Map provider ID to expected environment variable name."""
    mapping = {
        "openai":      "OPENAI_API_KEY",
        "google":      "GOOGLE_API_KEY",
        "xai":         "XAI_API_KEY",
        "openrouter":  "OPENROUTER_API_KEY",
        "groq":        "GROQ_API_KEY",
        "deepseek":    "DEEPSEEK_API_KEY",
    }
    return mapping.get(provider_id, f"{provider_id.upper()}_API_KEY")
