"""
restore_config_gen.py — Generate restore_config.py from WizardState.

The generated script restores critical openclaw.json fields after
`openclaw update` silently resets them (clobbered-file behaviour).

Critical fields that may be reset by openclaw update:
  - plugins.allow       → Mistral/Anthropic plugins fall silent if reset
  - plugins.entries     → custom specs and enabled flags get wiped
  - gateway.auth.rateLimit → rate-limiting disabled after update

Usage of generated script (run on HOST, not inside Docker):
  python3 ~/.openclaw/scripts/restore_config.py

Recommended: run after every `openclaw update` command.
"""
from pathlib import Path
from wizard.state import WizardState


def generate(state: WizardState) -> str:
    """Return restore_config.py content as string."""
    config_path = state.openclaw_dir / "openclaw.json"
    log_dir = state.openclaw_dir / "logs"

    return f'''\
#!/usr/bin/env python3
"""
restore_config.py — Restore critical openclaw.json fields after openclaw update.

Generated by openclaw-installer. Re-run the installer to regenerate.

IMPORTANT: Run this after every `openclaw update` command.
openclaw update may silently reset plugins.allow, plugins.entries, and
gateway.auth.rateLimit — causing Mistral and other providers to stop working.

Usage:
  python3 {config_path}/../scripts/restore_config.py

  Or add to your update workflow:
  openclaw update && python3 ~/.openclaw/scripts/restore_config.py
"""
import json
import logging
import shutil
from datetime import datetime, timezone
from pathlib import Path

CONFIG_PATH = Path("{config_path}")
LOG_DIR = Path("{log_dir}")
BACKUP_PATH = CONFIG_PATH.with_suffix(".json.pre-restore")

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] %(levelname)s %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)
log = logging.getLogger("restore_config")

# Fields restored by this script.
# Update these if your installer config changes.
MUST_HAVE_PLUGINS = {{
    "allow": ["mistral", "anthropic", "telegram"],
    "entries": {{
        "mistral": {{"enabled": True}},
        "anthropic": {{"enabled": True}},
        "telegram-approval-buttons": {{
            "spec": "telegram-approval-buttons@5.1.0",
        }},
    }},
}}

MUST_HAVE_GATEWAY_AUTH = {{
    "rateLimit": {{
        "maxAttempts": 10,
        "windowMs": 60000,
        "lockoutMs": 300000,
    }}
}}


def _deep_merge(base: dict, patch: dict) -> dict:
    """Recursively merge patch into base. patch values take precedence."""
    result = dict(base)
    for key, val in patch.items():
        if key in result and isinstance(result[key], dict) and isinstance(val, dict):
            result[key] = _deep_merge(result[key], val)
        else:
            result[key] = val
    return result


def main() -> None:
    if not CONFIG_PATH.exists():
        log.error("openclaw.json not found at %s", CONFIG_PATH)
        raise SystemExit(1)

    original = json.loads(CONFIG_PATH.read_text())

    # Backup before modifying
    shutil.copy2(CONFIG_PATH, BACKUP_PATH)
    log.info("Backup written: %s", BACKUP_PATH)

    patched = dict(original)

    # Restore plugins
    plugins_before = patched.get("plugins", {{}})
    patched["plugins"] = _deep_merge(plugins_before, MUST_HAVE_PLUGINS)

    # Restore gateway.auth
    gateway = dict(patched.get("gateway", {{}}))
    auth = dict(gateway.get("auth", {{}}))
    auth = _deep_merge(auth, MUST_HAVE_GATEWAY_AUTH)
    gateway["auth"] = auth
    patched["gateway"] = gateway

    CONFIG_PATH.write_text(json.dumps(patched, indent=2) + "\\n")

    # Report changes
    changes = []
    if patched.get("plugins") != original.get("plugins"):
        changes.append("plugins.allow / plugins.entries")
    if patched.get("gateway", {{}}).get("auth") != original.get("gateway", {{}}).get("auth"):
        changes.append("gateway.auth.rateLimit")

    if changes:
        log.info("Restored: %s", ", ".join(changes))
        print(f"\\u2713 restore_config: restored {{', '.join(changes)}}")
    else:
        log.info("No changes needed — config was already correct.")
        print("\\u2713 restore_config: nothing to restore (config already correct)")


if __name__ == "__main__":
    main()
'''


def write(state: WizardState) -> Path:
    """Write restore_config.py to scripts_dir. Returns path."""
    scripts_dir = state.openclaw_dir / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    target = scripts_dir / "restore_config.py"
    target.write_text(generate(state))
    target.chmod(0o755)
    return target
