"""
restore_gen.py — Generate restore_exec_approvals.py from WizardState.
The generated script re-writes exec-approvals.json at container start
(e.g. after an accidental overwrite by the gateway's doctor mode).

Docker-specific notes:
- Paths are container-internal (/home/node/.openclaw/...)
- Called via: docker compose exec openclaw-gateway python3 /scripts/restore_exec_approvals.py
- Or triggered by a cron job inside the container
"""
from pathlib import Path
from wizard.state import WizardState

# Container-internal paths (independent of host user)
_OPENCLAW   = "/home/node/.openclaw"
_SCRIPTS    = f"{_OPENCLAW}/scripts"
_WORKSPACE  = f"{_OPENCLAW}/workspace"


def generate(state: WizardState) -> str:
    """Return restore_exec_approvals.py content as string."""
    import json as _json

    # Read token from the already-written exec-approvals.json
    approvals_file = state.openclaw_dir / "exec-approvals.json"
    try:
        token = _json.loads(approvals_file.read_text())["socket"]["token"]
    except Exception:
        token = "REPLACE_WITH_SOCKET_TOKEN"

    socket_path = f"{_OPENCLAW}/exec-approvals.sock"

    # Build agent allowlists as Python literal (injected verbatim)
    agents_block = _agents_block(state)

    script = f'''#!/usr/bin/env python3
"""
restore_exec_approvals.py — Restore exec-approvals.json inside the OpenClaw container.

Generated by openclaw-installer. Re-run the installer to regenerate.

Usage:
  # Inside running container:
  docker compose exec openclaw-gateway python3 {_SCRIPTS}/restore_exec_approvals.py

  # Or via docker run:
  docker compose run --rm openclaw-gateway python3 {_SCRIPTS}/restore_exec_approvals.py
"""
import json
import logging
import time
from pathlib import Path

TARGET   = Path("{_OPENCLAW}/exec-approvals.json")
LOG_FILE = Path("{_OPENCLAW}/logs/restore-exec-approvals.log")

logging.basicConfig(
    filename=str(LOG_FILE),
    level=logging.INFO,
    format="[%(asctime)s] %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)
log = logging.getLogger()

APPROVALS = {{
    "version": 1,
    "socket": {{
        "path": "{socket_path}",
        "token": "{token}"
    }},
    "defaults": {{
        "security": "allowlist",
        "ask": "on-miss",
        "askFallback": "deny",
        "allowlist": [
            {{"pattern": "/usr/bin/python3",    "id": "d-python3-01"}},
            {{"pattern": "/usr/bin/ls",         "id": "d-ls-01"}},
            {{"pattern": "/usr/bin/cat",        "id": "d-cat-01"}},
            {{"pattern": "/usr/bin/grep",       "id": "d-grep-01"}},
            {{"pattern": "/usr/bin/head",       "id": "d-head-01"}},
            {{"pattern": "/usr/bin/tail",       "id": "d-tail-01"}},
            {{"pattern": "/usr/bin/find",       "id": "d-find-01"}},
            {{"pattern": "/usr/bin/wc",         "id": "d-wc-01"}},
            {{"pattern": "/usr/bin/df",         "id": "d-df-01"}},
            {{"pattern": "/usr/bin/curl",       "id": "d-curl-01"}},
            {{"pattern": "{_SCRIPTS}/health_check.py",     "id": "d-health-check-01"}},
            {{"pattern": "{_SCRIPTS}/morning_briefing.py", "id": "d-morning-briefing-01"}},
            {{"pattern": "{_SCRIPTS}/daily_digest.py",     "id": "d-daily-digest-01"}},
            {{"pattern": "{_SCRIPTS}/audit_integrity.py",  "id": "d-audit-integrity-01"}},
        ]
    }},
    "agents": {agents_block}
}}


def main() -> None:
    LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
    log.info("START: restore exec-approvals.json")
    time.sleep(2)  # brief wait for gateway socket
    TARGET.write_text(json.dumps(APPROVALS, indent=2))
    log.info("OK: exec-approvals.json restored at %s", str(TARGET))
    print("✓ exec-approvals.json restored")


if __name__ == "__main__":
    main()
'''
    return script


def _agents_block(state: WizardState) -> str:
    """Generate the agents dict as a Python literal string."""
    main_allowlist = [
        {"pattern": "/usr/bin/python3",    "id": "m-py-01"},
        {"pattern": "/usr/bin/git",        "id": "m-git-01"},
        {"pattern": "/usr/bin/bash",       "id": "m-bash-01"},
        {"pattern": "/bin/bash",           "id": "m-bash-02"},
        {"pattern": "/usr/bin/ls",         "id": "m-ls-01"},
        {"pattern": "/usr/bin/cat",        "id": "m-cat-01"},
        {"pattern": "/usr/bin/find",       "id": "m-find-01"},
        {"pattern": "/usr/bin/grep",       "id": "m-grep-01"},
        {"pattern": "/usr/bin/head",       "id": "m-head-01"},
        {"pattern": "/usr/bin/tail",       "id": "m-tail-01"},
        {"pattern": "/usr/bin/wc",         "id": "m-wc-01"},
        {"pattern": "/usr/bin/df",         "id": "m-df-01"},
        {"pattern": "/usr/bin/du",         "id": "m-du-01"},
        {"pattern": "/usr/bin/free",       "id": "m-free-01"},
        {"pattern": "/usr/bin/ps",         "id": "m-ps-01"},
        {"pattern": "/usr/bin/uptime",     "id": "m-uptime-01"},
        {"pattern": "/usr/bin/curl",       "id": "m-curl-01"},
        {"pattern": "/usr/bin/rsync",      "id": "m-rsync-01"},
        {"pattern": "/usr/bin/trash",      "id": "m-trash-01"},
        {"pattern": "/usr/bin/mkdir",      "id": "m-mkdir-01"},
        {"pattern": "/usr/bin/ln",         "id": "m-ln-01"},
        {"pattern": "/usr/bin/sort",       "id": "m-sort-01"},
        {"pattern": "/usr/bin/jq",         "id": "m-jq-01"},
        {"pattern": "/usr/bin/diff",       "id": "m-diff-01"},
        {"pattern": "/usr/bin/stat",       "id": "m-stat-01"},
        {"pattern": "/usr/bin/echo",       "id": "m-echo-01"},
        {"pattern": "/usr/bin/env",        "id": "m-env-01"},
        {"pattern": "/usr/bin/which",      "id": "m-which-01"},
        {"pattern": "/usr/bin/sed",        "id": "m-sed-01"},
        {"pattern": "/usr/bin/awk",        "id": "m-awk-01"},
        {"pattern": f"{_SCRIPTS}/health_check.py",    "id": "m-health-check-01"},
        {"pattern": f"{_SCRIPTS}/audit_integrity.py", "id": "m-audit-integrity-01"},
        {"pattern": f"{_WORKSPACE}/skills/web-search/search.py",       "id": "m-web-search-01"},
        {"pattern": f"{_WORKSPACE}/skills/docs-summarize/summarize.py","id": "m-docs-summarize-01"},
    ]

    import json as _json

    agents = {
        "main": {
            "security": "allowlist",
            "ask": "on-miss",
            "askFallback": "deny",
            "autoAllowSkills": True,
            "allowlist": main_allowlist,
        }
    }
    return _json.dumps(agents, indent=4)


def write(state: WizardState) -> Path:
    """Write restore_exec_approvals.py and start.sh to scripts_dir."""
    scripts_dir = state.openclaw_dir / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)

    # restore script
    restore = scripts_dir / "restore_exec_approvals.py"
    restore.write_text(generate(state))
    restore.chmod(0o755)

    # entrypoint wrapper — runs restore then launches gateway
    start_sh = scripts_dir / "start.sh"
    start_sh.write_text(_start_sh())
    start_sh.chmod(0o755)

    return restore


def _start_sh() -> str:
    return f'''#!/bin/bash
# start.sh — OpenClaw container entrypoint
# Restores exec-approvals.json on every start, then launches the gateway.
set -e

echo "[✓] Restoring exec-approvals.json..."
python3 {_SCRIPTS}/restore_exec_approvals.py

echo "[✓] Starting OpenClaw gateway..."
exec node dist/index.js
'''
