"""
update_gen.py — Generate UPDATE.md in the workspace root.
Documents the update flow for Docker-based OpenClaw installations.
Generated once at install time; the user keeps this alongside docker-compose.yml.
"""
from pathlib import Path
from wizard.state import WizardState


def generate(state: WizardState) -> str:
    """Return UPDATE.md content as string."""
    compose_file = state.openclaw_dir / "docker-compose.yml"
    scripts_dir = state.scripts_dir

    return f"""# OpenClaw Update Guide

> Generated by openclaw-installer. Update these instructions when you change your setup.

## Standard Update Flow

Run these commands in order. Do **not** skip the backup step.

### 1. Backup first

```bash
docker compose -f {compose_file} exec openclaw-gateway \\
    python3 /home/node/.openclaw/scripts/daily_backup.py
```

### 2. Pull new image

```bash
docker compose -f {compose_file} pull openclaw-gateway
```

### 3. Skip onboarding on restart

The `OPENCLAW_SKIP_ONBOARDING=1` flag prevents the agent from running the
first-run onboarding flow when the container restarts with a new image.

```bash
OPENCLAW_SKIP_ONBOARDING=1 docker compose -f {compose_file} up -d openclaw-gateway
```

### 4. Run doctor

```bash
docker compose -f {compose_file} run --rm openclaw-cli doctor --json
```

Review the output. If `openclaw.json` was reset (known behaviour on some updates),
restore it:

```bash
docker compose -f {compose_file} exec openclaw-gateway \\
    python3 {scripts_dir}/restore_config.py
```

### 5. Restore exec-approvals (if needed)

If exec-approvals.json was overwritten:

```bash
docker compose -f {compose_file} exec openclaw-gateway \\
    python3 /home/node/.openclaw/scripts/restore_exec_approvals.py
```

---

## Device Approval (after update)

If the Control UI blocks access after restart, approve the new device session:

```bash
# List pending device requests
docker compose -f {compose_file} run --rm openclaw-cli devices list

# Approve a specific request
docker compose -f {compose_file} run --rm openclaw-cli devices approve <requestId>
```

---

## Rollback

If the new image is broken, roll back to the previous image:

```bash
# Stop the new container
docker compose -f {compose_file} down

# Pull a specific version tag (check GitHub releases for available tags)
# e.g. ghcr.io/openclaw/openclaw:extended-stable (always points to last stable)
docker compose -f {compose_file} up -d
```

---

## Verify

After the update, send your agent:

```
/status
```

The response should include the new version number and confirm all tools are working.

---

*Last generated by openclaw-installer. Re-run the installer to regenerate.*
"""


def write(state: WizardState) -> Path:
    """Write UPDATE.md to openclaw_dir. Returns path."""
    target = state.openclaw_dir / "UPDATE.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(generate(state).encode("utf-8"))
    return target
